# Exclude a variety of commonly ignored directories.
extend-exclude = [ "venv", "docs/conf.py" ]
# Same as Black.
line-length = 99

# Assume Python 3.14
target-version = "py314"

# Enable using ruff with notebooks
extend-include = [ "*.ipynb" ]

[lint]
select = [ "ALL" ]

ignore = [
  "D202",
  "D213",
  "D203",
  "ISC002",
  "RUF001",
  "RUF002",
  "RUF003",
  "B008",
  # Covered by formatter
  "ISC001",
  "COM812",
]
external = [ "DOC" ]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"tests/*" = [ "ANN201", "ANN202", "ARG001", "D401", "D404", "S101" ]
"openapi_diagram/server/app.py" = [ "ANN201" ]
"openapi_diagram/cli/*" = [ "FBT001" ]

[lint.isort]
required-imports = [ "from __future__ import annotations" ]
known-first-party = [ "openapi_diagram" ]
force-single-line = true

[lint.pydocstyle]
convention = "numpy"
