name: "Tests"
on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python "3.11"
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install .[docs]
      - name: Show installed dependencies
        run: |
          pip freeze
      - name: Build docs
        run: make --directory=docs clean html

  docs-link:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python "3.11"
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install .[docs]
      - name: Show installed dependencies
        continue-on-error: true
        run: |
          pip freeze
      - name: Build docs
        run: make --directory=docs clean linkcheck

  test:
    runs-on: ${{ matrix.os }}
    needs: [pre-commit, docs]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11", "3.12"]

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2
        with:
          # Skip to run brew update command on macOS, duo to
          # https://github.com/ts-graphviz/setup-graphviz/issues/457
          macos-skip-brew-update: "true"
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U ".[test]"
          python -m pip install -r requirements_pinned.txt
      - name: Run tests
        run: |
          python -m pytest --cov=./ --cov-report term --cov-report xml --cov-config .coveragerc tests
      - name: Codecov Upload
        continue-on-error: true
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          name: ${{ matrix.os }}-py${{ matrix.python-version }}

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python "3.11"
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install -U hatch

      - name: Build dist
        run: hatch build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          print-hash: true
